import eslintConfigPrettier from "eslint-config-prettier";

export default [
  {
    files: ["**/*.{js,mjs,cjs,jsx}"],
    ignores: ["dist/**", "node_modules/**", ".kilo/**", "public/sw.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        caches: "readonly",
        serviceWorker: "readonly",
        Notification: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        crypto: "readonly",
        URL: "readonly",
        location: "readonly",
        history: "readonly",
        scroll: "readonly",
        scrollIntoView: "readonly",
        HTMLCollection: "readonly",
        NodeList: "readonly",
        Element: "readonly",
        Node: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        CanvasRenderingContext2D: "readonly",
        L: "readonly",
        Supabase: "readonly",
        EventTarget: "readonly",
        File: "readonly",
        FileReader: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        URLSearchParams: "readonly",
        BroadcastChannel: "readonly",
        Notification: "readonly",
        Promise: "readonly",
        Symbol: "readonly",
        Reflect: "readonly",
        Proxy: "readonly",
        Intl: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Number: "readonly",
        String: "readonly",
        Boolean: "readonly",
        Array: "readonly",
        Object: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
        Int8Array: "readonly",
        Uint8Array: "readonly",
        Uint8ClampedArray: "readonly",
        Int16Array: "readonly",
        Uint16Array: "readonly",
        Int32Array: "readonly",
        Uint32Array: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        BigInt: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {},
    rules: {
      "no-unused-vars": ["error", { args: "after-used", caughtErrors: "none", argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-undef": "error",
    },
  },
  eslintConfigPrettier,
];