/**
 * @file AiInsightPanel component.
 * @description The "AI Assistance" card on the user dashboard. It is
 * subscription-aware: subscribers get a working analysis panel, everyone
 * else gets a locked card that explains the benefit and links to pricing.
 */

import { el } from "../utils/dom.js";
import { navigate } from "../router/index.js";
import { renderToast } from "./ToastContainer.jsx";
import { ANALYSIS_TYPES, runBusinessAnalysis } from "../services/ai.service.js";
import { FEATURES } from "../data/plans.js";
import { getLimit } from "../services/subscription.service.js";

/**
 * Colour-codes a health score.
 *
 * @param {number} score - A 0–100 score.
 * @returns {string} A CSS colour.
 */
function scoreColor(score) {
  if (score >= 70) return "#16a34a";
  if (score >= 45) return "#d97706";
  return "#dc2626";
}

/**
 * Creates the locked "upgrade to unlock" state.
 *
 * @param {Object} options - Options.
 * @param {string} options.blurb - Why the feature is worth paying for.
 * @param {string} [options.planName="Pro Growth"] - Suggested plan.
 * @returns {HTMLElement}
 */
function renderLockedState({ blurb, planName = "Pro Growth" }) {
  const wrap = el("div", "mmb-lock");
  wrap.appendChild(el("p", null, blurb));
  wrap.appendChild(
    el(
      "p",
      "mmb-note",
      "AI business analysis is included from the Pro plan. It reads your revenue, costs and customers, then tells you the three things to fix this month."
    )
  );
  const btn = el("button", "mmb-btn", `Upgrade to ${planName}`);
  btn.type = "button";
  btn.addEventListener("click", () => navigate("/subscriptions"));
  wrap.appendChild(btn);
  return wrap;
}

/**
 * Renders the results of an analysis into a container.
 *
 * @param {HTMLElement} container - Target container.
 * @param {Object} analysis - Result from `runBusinessAnalysis`.
 * @returns {void}
 */
function renderAnalysis(container, analysis) {
  container.innerHTML = "";

  const scoreRow = el("div", "mmb-ai__score");
  const ring = el("div", "mmb-ai__ring", `${analysis.score}`);
  ring.style.background = scoreColor(analysis.score);
  ring.setAttribute("aria-label", `Business health score ${analysis.score} out of 100`);
  const scoreText = el("div");
  scoreText.appendChild(el("p", "mmb-ai__headline", analysis.headline));
  scoreText.appendChild(
    el(
      "p",
      "mmb-ai__source",
      analysis.source === "ai"
        ? `Focus: ${analysis.focus} · generated by the AI service`
        : `Focus: ${analysis.focus} · generated on-device from your numbers`
    )
  );
  scoreRow.appendChild(ring);
  scoreRow.appendChild(scoreText);
  container.appendChild(scoreRow);

  if (analysis.insights?.length) {
    const insights = el("div", "mmb-ai__section");
    insights.appendChild(el("h4", null, "What the numbers say"));
    analysis.insights.forEach((insight) => {
      const box = el("div", `mmb-ai__insight mmb-ai__insight--${insight.severity || "low"}`);
      box.appendChild(el("strong", null, insight.title));
      box.appendChild(el("p", null, insight.body));
      insights.appendChild(box);
    });
    container.appendChild(insights);
  }

  if (analysis.actions?.length) {
    const actions = el("div", "mmb-ai__section");
    actions.appendChild(el("h4", null, "Do this next month"));
    analysis.actions.forEach((action, index) => {
      const row = el("div", "mmb-ai__action");
      row.appendChild(el("span", null, `${index + 1}.`));
      row.appendChild(el("span", null, action));
      actions.appendChild(row);
    });
    container.appendChild(actions);
  }
}

/**
 * Creates the AI Assistance panel.
 *
 * @param {Object} options - Options.
 * @param {Object|null} options.subscription - The user's subscription.
 * @param {string|null} options.userId - The user id.
 * @param {boolean} options.unlocked - Whether the plan includes AI analysis.
 * @param {Object} options.growth - `computeGrowth()` result.
 * @param {Object[]} options.businesses - The user's listings.
 * @param {number} options.completedModules - Completed module count.
 * @param {number} options.totalModules - Total module count.
 * @param {number} options.certificates - Certificates earned.
 * @param {number} options.remaining - Analyses left this month.
 * @param {Function} [options.onUsed] - Called after an analysis runs.
 * @returns {HTMLElement}
 */
export function AiInsightPanel(options) {
  const {
    subscription,
    userId = null,
    unlocked,
    growth,
    businesses = [],
    completedModules = 0,
    totalModules = 0,
    certificates = 0,
    remaining = 0,
    onUsed,
  } = options;

  const card = el("section", unlocked ? "mmb-card" : "mmb-card mmb-card--locked");
  const head = el("div", "mmb-card__head");
  head.appendChild(el("h2", "mmb-card__title", "🤖 AI Assistance & Analysis"));
  card.appendChild(head);

  if (!unlocked) {
    card.appendChild(
      renderLockedState({
        blurb: "Get a plain-language read on your business every month.",
      })
    );
    return card;
  }

  const monthlyLimit = getLimit(subscription, "aiAnalysesPerMonth", 0);
  const quotaNote = el("p", "mmb-card__hint");
  const paintQuota = (left) => {
    quotaNote.textContent =
      monthlyLimit === Number.POSITIVE_INFINITY
        ? "Unlimited analyses on your plan."
        : `${left} of ${monthlyLimit} analyses left this month · resets on the 1st`;
  };
  paintQuota(remaining);
  card.appendChild(quotaNote);

  const controls = el("div", "mmb-form-grid");
  const typeSelect = el("select", "mmb-select");
  ANALYSIS_TYPES.forEach((type) => {
    const option = el("option", null, type.label);
    option.value = type.id;
    typeSelect.appendChild(option);
  });

  const typeField = el("label", "mmb-field", "What should the AI look at?");
  typeField.appendChild(typeSelect);
  controls.appendChild(typeField);

  const questionField = el("label", "mmb-field", "Ask anything (optional)");
  const questionInput = el("input", "mmb-input");
  questionInput.type = "text";
  questionInput.placeholder = "e.g. Should I hire a second person?";
  questionField.appendChild(questionInput);
  controls.appendChild(questionField);
  card.appendChild(controls);

  const runBtn = el("button", "mmb-btn", "Run analysis");
  runBtn.type = "button";
  card.appendChild(runBtn);

  const output = el("div", "mmb-ai__output");
  card.appendChild(output);

  runBtn.addEventListener("click", async () => {
    runBtn.disabled = true;
    const previousLabel = runBtn.textContent;
    runBtn.textContent = "Analysing…";
    output.innerHTML = "";

    const { ok, data, error, remaining: left } = await runBusinessAnalysis({
      subscription,
      userId,
      growth,
      businesses,
      completedModules,
      totalModules,
      certificates,
      type: typeSelect.value,
      question: questionInput.value.trim(),
    });

    runBtn.disabled = false;
    runBtn.textContent = previousLabel;

    if (!ok) {
      renderToast(error || "The analysis could not be completed.", "warning");
      return;
    }

    renderAnalysis(output, data);
    paintQuota(left);
    if (typeof onUsed === "function") onUsed(left);
  });

  return card;
}

export { FEATURES, renderAnalysis };
export default AiInsightPanel;
